In [ ]:
import pandas as pd
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
dataset = pd.read_csv('/content/milknew.csv')
dataset

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0     6.6          35      1     0     1          0     254    high
1     6.6          36      0     1     0          1     253    high
2     8.5          70      1     1     1          1     246     low
3     9.5          34      1     1     0          1     255     low
4     6.6          37      0     0     0          0     255  medium
...   ...         ...    ...   ...   ...        ...     ...     ...
1054  6.7          45      1     1     0          0     247  medium
1055  6.7          38      1     0     1          0     255    high
1056  3.0          40      1     1     1          1     255     low
1057  6.8          43      1     0     1          0     250    high
1058  8.6          55      0     1     1          1     255     low

[1059 rows x 8 columns]

In [ ]:
dataset.shape


(1059, 8)

In [ ]:
dataset.describe()

pH   Temprature        Taste         Odor         Fat   \
count  1059.000000  1059.000000  1059.000000  1059.000000  1059.000000   
mean      6.630123    44.226629     0.546742     0.432483     0.671388   
std       1.399679    10.098364     0.498046     0.495655     0.469930   
min       3.000000    34.000000     0.000000     0.000000     0.000000   
25%       6.500000    38.000000     0.000000     0.000000     0.000000   
50%       6.700000    41.000000     1.000000     0.000000     1.000000   
75%       6.800000    45.000000     1.000000     1.000000     1.000000   
max       9.500000    90.000000     1.000000     1.000000     1.000000   

         Turbidity       Colour  
count  1059.000000  1059.000000  
mean      0.491029   251.840415  
std       0.500156     4.307424  
min       0.000000   240.000000  
25%       0.000000   250.000000  
50%       0.000000   255.000000  
75%       1.000000   255.000000  
max       1.000000   255.000000

##2. Data Preprocessing

In [ ]:
dataset.dropna(axis=0,inplace=True)

In [ ]:
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,-1]

In [ ]:
Y.unique()

array(['high', 'low', 'medium'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.25,random_state=0)

In [ ]:
X_train

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour
661   6.5          38      1     0     0          0     255
37    7.4          65      0     0     0          0     255
969   6.7          45      1     1     0          0     247
158   6.7          45      1     1     0          0     247
40    6.8          38      0     0     0          0     255
...   ...         ...    ...   ...   ...        ...     ...
1033  6.6          38      0     0     0          0     255
763   5.6          50      0     1     1          1     255
835   4.7          38      1     0     1          0     255
559   9.0          43      1     0     1          1     250
684   6.5          38      1     0     0          0     255

[794 rows x 7 columns]

In [ ]:
Y_train

661     medium
37         low
969     medium
158     medium
40      medium
         ...  
1033    medium
763        low
835        low
559        low
684     medium
Name: Grade, Length: 794, dtype: object

In [ ]:
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [ ]:
X_train

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour
661   6.5          38      1     0     0          0     255
37    7.4          65      0     0     0          0     255
969   6.7          45      1     1     0          0     247
158   6.7          45      1     1     0          0     247
40    6.8          38      0     0     0          0     255
...   ...         ...    ...   ...   ...        ...     ...
1033  6.6          38      0     0     0          0     255
763   5.6          50      0     1     1          1     255
835   4.7          38      1     0     1          0     255
559   9.0          43      1     0     1          1     250
684   6.5          38      1     0     0          0     255

[794 rows x 7 columns]

##3.Modeling

##Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,Y_train)

DecisionTreeClassifier()

DecisionTreeClassifier()

In [ ]:
Y_pred=model.predict(X_test)
Y_pred.shape

(265,)

In [ ]:
Y_pred

array(['high', 'low', 'medium', 'low', 'high', 'medium', 'low', 'high',
       'high', 'medium', 'low', 'high', 'medium', 'medium', 'high',
       'medium', 'high', 'high', 'high', 'low', 'high', 'low', 'medium',
       'high', 'high', 'low', 'high', 'high', 'low', 'medium', 'high',
       'low', 'low', 'medium', 'high', 'high', 'low', 'medium', 'high',
       'low', 'high', 'medium', 'high', 'low', 'medium', 'low', 'high',
       'low', 'medium', 'low', 'high', 'medium', 'medium', 'medium',
       'low', 'medium', 'medium', 'low', 'medium', 'low', 'medium', 'low',
       'medium', 'high', 'low', 'medium', 'low', 'medium', 'medium',
       'high', 'high', 'medium', 'medium', 'high', 'medium', 'medium',
       'medium', 'low', 'high', 'medium', 'low', 'medium', 'medium',
       'low', 'medium', 'medium', 'high', 'low', 'low', 'low', 'medium',
       'high', 'medium', 'low', 'high', 'medium', 'low', 'high', 'medium',
       'medium', 'high', 'medium', 'low', 'medium', 'high', 'high',
   

In [ ]:
#from sklearn.linear_model import LogisticRegression
#classifier = LogisticRegression()
#classifier.fit(X_train,Y_train)

In [ ]:
#Y_pred = classifier.predict(X_test)
#probs_y=classifier.predict_proba(X_test)

In [ ]:
#Y_pred

In [ ]:
#probs_y

In [ ]:
#probs_y = np.round(probs_y, 2)
#probs_y

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_test,Y_pred)
print(confusion_matrix)

[[80  0  1]
 [ 0 90  1]
 [ 0  0 93]]


##4. Evaluation

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score

print('Accuracy Score =',accuracy_score(Y_test, Y_pred)*100,'%')
print('Precision Macro Score =',precision_score(Y_test, Y_pred,average = 'macro')*100,'%')
print('Recall_Score =',recall_score(Y_test, Y_pred, average = 'macro')*100,'%')

Accuracy Score = 99.24528301886792 %
Precision Macro Score = 99.29824561403508 %
Recall_Score = 99.22217699995478 %


In [ ]:
precision=99.29824561403508
recall=99.22217699995478
f1_score = (2*recall*precision)/(recall+precision)
print('f1_score = ',f1_score,'%')


f1_score =  99.26019673309375 %


In [ ]:
#import joblib

In [ ]:
#joblib.dump(model, 'DuoRookies.joblib')

['RRookiesfinalmodel.joblib']

In [ ]:
import pickle 

In [ ]:
pickle_out = open("Rookiesproject.pkl", mode = "wb") 

In [ ]:
pickle.dump(model, pickle_out)


ValueError: ignored

In [ ]:
pickle_out.close()